mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: [MYSQL_USER]
  password: [MYSQL_PASS]
  database: [MYSQL_DATABASE]
  socket: /cloudsql/[YOUR_INSTANCE_CONNECTION_NAME]

development:
  <<: *mysql_settings

production:
  <<: *mysql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
