# [START settings]
default: &default
  project_id: [YOUR_PROJECT_ID]
  gcs_bucket: [YOUR_BUCKET_NAME]
  pubsub_topic: [YOUR_PUBSUB_TOPIC]
  pubsub_subscription: [YOUR_PUBSUB_SUBSCRIPTION]
  oauth2:
    client_id: [YOUR_CLIENT_ID]
    client_secret: [YOUR_CLIENT_SECRET]
# [END settings]

development:
  <<: *default

production:
  <<: *default
