default: &default
# Google Cloud SQL Sample Database Configuration
# ----------------------------------------------
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: [MYSQL_USER]
#   password: [MYSQL_PASS]
#   database: [MYSQL_DATABASE]
#   socket: /cloudsql/[YOUR_INSTANCE_CONNECTION_NAME]

# Google Cloud Datastore Sample Database Configuration
# ----------------------------------------------------
#   dataset_id: [YOUR_PROJECT_ID]

# PostgreSQL Sample Database Configuration
# ----------------------------------------
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: [YOUR_POSTGRES_USER]
#   password: [YOUR_POSTGRES_PASSWORD]
#   host: [YOUR_POSTGRES_IPV4_ADDRESS]
#   database: [YOUR_POSTGRES_DATABASE]

development:
  <<: *default

production:
  <<: *default

# Test configuration
test:
  # Datastore
  dataset_id: [YOUR_TEST_PROJECT_ID]
  # SQL
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
